Repository TEAM-NULL-NULL/NBE5-6-3-Team05_prep, pull requests merged in 2025-06, with the labels that each got.

#1 Kms
  src/main/java/com/grepp/moodlink/app/model/admin/book/AdminBookRepositoryCustom.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/AdminBookRepositoryImpl.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/AdminBookService.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/AdminMusicRepositoryCustom.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/AdminMusicRepositoryImpl.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/AdminMusicService.java
  src/main/java/com/grepp/moodlink/app/model/data/book/BookGenreRepository.java
  src/main/java/com/grepp/moodlink/app/model/data/book/BookService.java
  src/main/java/com/grepp/moodlink/app/model/data/book/dto/BookDto.java
  src/main/java/com/grepp/moodlink/app/model/data/book/entity/Book.java
  src/main/java/com/grepp/moodlink/app/model/data/book/entity/BookGenre.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicGenreRepository.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicService.java
  src/main/java/com/grepp/moodlink/app/model/data/music/dto/MusicDto.java
  src/main/java/com/grepp/moodlink/app/model/data/music/entity/Music.java
  src/main/java/com/grepp/moodlink/app/model/data/music/entity/MusicGenre.java
  src/main/java/com/grepp/moodlink/app/model/recomend/LikeService.java
Labels: 🛠 backend, 🔧 enhancement

#2 Kdg - 기존 키워드에서 LLM 결과 저장되어있는 추천 결과값을 불러올 수 있도록 수정
  src/main/java/com/grepp/moodlink/app/controller/web/recommend/RecommendController.java
  src/main/java/com/grepp/moodlink/app/model/keyword/KeywordRepository.java
  src/main/java/com/grepp/moodlink/app/model/keyword/KeywordService.java
  src/main/java/com/grepp/moodlink/app/model/keyword/entity/KeywordSelection.java
  src/main/java/com/grepp/moodlink/app/model/keyword/entity/KeywordSelectionDetail.java
  src/main/java/com/grepp/moodlink/app/model/llm/EmbeddingService.java
  src/main/java/com/grepp/moodlink/app/model/llm/LlmScheduler.java
  src/main/java/com/grepp/moodlink/app/model/llm/LlmService.java
  src/main/java/com/grepp/moodlink/app/model/llm/RecommendationRepository.java
  src/main/java/com/grepp/moodlink/app/model/llm/RecommendationService.java
  src/main/java/com/grepp/moodlink/app/model/llm/code/ContentType.java
  src/main/java/com/grepp/moodlink/app/model/llm/entity/Recommendation.java
  src/main/java/com/grepp/moodlink/app/model/member/entity/Member.java
  src/main/resources/templates/recommend/recommend.html
  src/test/java/com/grepp/moodlink/app/model/llm/RecommendationServiceTest.java
Labels: 🛠 backend, 🔧 enhancement

#4 LKH - 검색기능 개선
  src/main/java/com/grepp/moodlink/app/model/data/book/BookRepositoryImpl.java
  src/main/java/com/grepp/moodlink/app/model/data/music/MusicRepositoryImpl.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/home/mainPage.html
  src/main/resources/templates/home/search.html
Labels: ✅ done, ✨ feature, 🛠 backend, 🔧 enhancement

#7 Kms - api를 통해 정보를 자동입력하여 컨텐츠 추가하기
  src/main/java/com/grepp/moodlink/app/controller/api/admin/AdminApiLookuplController.java
  src/main/java/com/grepp/moodlink/app/controller/web/admin/payload/BookAddRequest.java
  src/main/java/com/grepp/moodlink/app/controller/web/admin/payload/MovieAddRequest.java
  src/main/java/com/grepp/moodlink/app/controller/web/admin/payload/MusicAddRequest.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/AdminBookService.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/BookLookupService.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/dto/NaverBookDto.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/dto/NaverDto.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/repository/AdminBookGenreRepository.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/repository/AdminBookRepository.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/repository/AdminBookRepositoryCustom.java
  src/main/java/com/grepp/moodlink/app/model/admin/book/repository/AdminBookRepositoryImpl.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/AdminMovieService.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/MovieLookupService.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/dto/TmdbDto.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/dto/TmdbMovieDto.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/repository/AdminGenreRepository.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/repository/AdminMovieRepository.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/repository/AdminMovieRepositoryCustom.java
  src/main/java/com/grepp/moodlink/app/model/admin/movie/repository/AdminMovieRepositoryImpl.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/AdminMusicService.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/MusicLookupService.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/repository/AdminMusicGenreRepository.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/repository/AdminMusicRepository.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/repository/AdminMusicRepositoryCustom.java
  src/main/java/com/grepp/moodlink/app/model/admin/music/repository/AdminMusicRepositoryImpl.java
  src/main/java/com/grepp/moodlink/infra/config/RestTemplateConfig.java
  src/main/resources/application.properties
  src/main/resources/static/css/admin/contents-add.css
  src/main/resources/templates/admin/contents/books-add.html
  src/main/resources/templates/admin/contents/movies-add.html
  src/main/resources/templates/admin/contents/music-add.html
Labels: ✨ feature, 🛠 backend, 🔧 enhancement
